# Generated by Django 5.2.3 on 2025-06-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDatePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date of the promotion period')),
                ('end_date', models.DateField(help_text='End date of the promotion period')),
                ('description', models.CharField(help_text='Description of the promotion', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Special Date Promotion',
                'verbose_name_plural': 'Special Date Promotions',
                'ordering': ['-start_date'],
            },
        ),
    ]
