# Generated by Django 5.2.3 on 2025-06-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_specialdatepromotion_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialdatepromotion',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed discount amount in pesos', max_digits=10),
        ),
    ]
