# Generated by Django 5.2.3 on 2025-06-30 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_specialdatepromotion_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialdatepromotion',
            name='discount_percentage',
        ),
    ]
