# Generated by Django 5.2.3 on 2025-07-01 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVO')), fields=('user', 'cart_type', 'status'), name='unique_active_cart_per_user_type'),
        ),
    ]
